
from sqlalchemy import Column, Integer, String, Date
from sqlalchemy.ext.declarative import declarative_base
from config.db import meta, engine, Base

Base = declarative_base()

class GestionCorrupcion(Base):
    __tablename__ = "riesgo_corrupcion"
    
    referencia = Column(Integer, primary_key=True, unique=True)
    proceso = Column(String(255))
    objetivo = Column(String(255))
    alcance = Column(String(255))
    descripcion_riesgo = Column(String(255))
    causa_inmediata = Column(String(255))
    causa_raiz = Column(String(255))
    clasificacion_riesgo = Column(String(255))
    probabilidad = Column(String(255))
    impacto = Column(String(255))
    perfil_riesgo = Column(String(255))
    zona_riesgo_inherente = Column(String(255))
    no_control = Column(Integer)
    descripcion_control = Column(String(255))
    proposito_control = Column(String(255))
    responsable1 = Column(String(255))
    responsable2 = Column(String(255))
    periodicidad = Column(String(255))
    como_se_realiza_control = Column(String(255))
    que_pasa_observaciones = Column(String(255))
    evidencia_ejecucion_control = Column(String(255))
    calificacion_diseno_control = Column(String(255))
    evaluacion_diseno_control = Column(String(255))
    evaluacion_ejecucion_control = Column(String(255))
    solidez_individual_control = Column(String(255))
    aplica_plan_accion = Column(String(255))
    accion_fortalecer_control = Column(String(255))
    solidez_conjunto_controles = Column(String(255))
    controles_disminuyen_probabilidad = Column(String(255))
    controles_disminuyen_impacto = Column(String(255))
    desplazamiento_probabilidad = Column(String(255))
    desplazamiento_impacto = Column(String(255))
    probabilidad_residual = Column(String(255))
    impacto_residual = Column(String(255))
    perfil_riesgo_residual = Column(String(255))
    zona_riesgo_residual = Column(String(255))
    tratamiento_riesgo_residual = Column(String(255))
    accion_plan_manejo_riesgos = Column(String(255))
    responsable_plan_manejo_riesgos = Column(String(255))
    fecha_programada_plan_manejo = Column(Date)
    fecha_seguimiento_plan_manejo = Column(Date)
    seguimiento_primer_trimestre_plan_manejo = Column(String(255))
    fecha_seguimiento_segundo_trimestre = Column(Date)
    seguimiento_segundo_trimestre_plan_manejo = Column(String(255))
    fecha_seguimiento_tercer_trimestre = Column(Date)
    seguimiento_tercer_trimestre_plan_manejo = Column(String(255))
    fecha_seguimiento_cuarto_trimestre = Column(Date)
    seguimiento_cuarto_trimestre_plan_manejo = Column(String(255))
    estado_plan_manejo_riesgos = Column(String(255))
    fecha_seguimiento_primer_trimestre_controles = Column(Date)
    seguimiento_primer_trimestre_controles = Column(String(255))
    responsable_primer_trimestre_controles = Column(String(255))
    evidencia_primer_trimestre_controles = Column(String(255))
    efectividad_primer_trimestre_controles = Column(String(255))
    fecha_seguimiento_segundo_trimestre_controles = Column(Date)
    seguimiento_segundo_trimestre_controles = Column(String(255))
    responsable_segundo_trimestre_controles = Column(String(255))
    evidencia_segundo_trimestre_controles = Column(String(255))
    efectividad_segundo_trimestre_controles = Column(String(255))
    fecha_seguimiento_tercer_trimestre_controles = Column(Date)
    seguimiento_tercer_trimestre_controles = Column(String(255))
    responsable_tercer_trimestre_controles = Column(String(255))
    evidencia_tercer_trimestre_controles = Column(String(255))
    efectividad_tercer_trimestre_controles = Column(String(255))
    fecha_seguimiento_cuarto_trimestre_controles = Column(Date)
    seguimiento_cuarto_trimestre_controles = Column(String(255))
    responsable_cuarto_trimestre_controles = Column(String(255))
    evidencia_cuarto_trimestre_controles = Column(String(255))
    efectividad_cuarto_trimestre_controles = Column(String(255))
    actividades_contingencia = Column(String(255))
    fecha_materializacion_riesgo_contingencia = Column(Date)
    causa_materializacion_contingencia = Column(String(255))
    seguimiento_contingencia = Column(String(255))
    fecha_seguimiento_segunda_linea_defensa = Column(Date)
    seguimiento_control_soportes_segunda_linea = Column(String(255))
    seguimiento_plan_manejo_riesgos_soportes_segunda_linea = Column(String(255))
    fecha_evaluacion_tercera_linea_defensa = Column(Date)
    evaluacion_control_tercera_linea = Column(String(255))
    efectividad_control_tercera_linea = Column(String(255))
    
Base.metadata.create_all(bind=engine)